### ISSUE TITLE
Increase coverage of complex methods

### ISSUE THREAD

**Issue by jlundhol** [dd2480-12/jsoup#9]
Add tests to increase coverage of one of the following methods (current coverage in parentheses):

* Helper.HttpConnection::Response::Execute (92.7)
* Helper.DataUtil::parseInputStream (92.2)
* Select.QueryParser::findElements (97.2)
* Parser.TokenQueue::chompBalanced (98.4)
* Parser.HtmlTreeBuilder::resetInsertionMode (69)

**Comment by 9leks** [comment]
we need to add test to complex functions, not necessarily the ones we analyzed
